name: Generate Docs Artifact

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.9.4
        
