name: Generate Docs Artifact

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: |
          git clone https://github.com/GugaLincon/behavior-tree.git
          cd behavior-tree
      
      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.9.4
      
      - name: Save as artifact
        run: |
          dir
        
